//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaStorageServer.FaExportService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EExportFormat", Namespace="http://schemas.datacontract.org/2004/07/FaExportService")]
    public enum EExportFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Csv = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaExportService.IExportService")]
    public interface IExportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportService/ExportEventsToFile", ReplyAction="http://tempuri.org/IExportService/ExportEventsToFileResponse")]
        void ExportEventsToFile(FaStorageServer.FaExportService.EExportFormat exportType, System.Collections.Generic.List<Infrastructure.Models.CEventInfo> events, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportService/ExportEventsToFile", ReplyAction="http://tempuri.org/IExportService/ExportEventsToFileResponse")]
        System.Threading.Tasks.Task ExportEventsToFileAsync(FaStorageServer.FaExportService.EExportFormat exportType, System.Collections.Generic.List<Infrastructure.Models.CEventInfo> events, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExportServiceChannel : FaStorageServer.FaExportService.IExportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportServiceClient : System.ServiceModel.ClientBase<FaStorageServer.FaExportService.IExportService>, FaStorageServer.FaExportService.IExportService {
        
        public ExportServiceClient() {
        }
        
        public ExportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExportEventsToFile(FaStorageServer.FaExportService.EExportFormat exportType, System.Collections.Generic.List<Infrastructure.Models.CEventInfo> events, string path) {
            base.Channel.ExportEventsToFile(exportType, events, path);
        }
        
        public System.Threading.Tasks.Task ExportEventsToFileAsync(FaStorageServer.FaExportService.EExportFormat exportType, System.Collections.Generic.List<Infrastructure.Models.CEventInfo> events, string path) {
            return base.Channel.ExportEventsToFileAsync(exportType, events, path);
        }
    }
}
